export const STOPS_SCREEN = 'STOPS_SCREEN'


// Actions
export const GET_BUS_STOPS = 'GET_BUS_STOPS'
export const GET_DEPARTURES = 'GET_DEPARTURES'
export const SEARCH_TEXT_CHANGED = 'SEARCH_TEXT_CHANGED'
export const SET_SELECTED_STOP = 'SET_SELECTED_STOP'
export const REQUEST_LOCATION = 'REQUEST_LOCATION'